import { Header } from '@/components/containers/header/header';
import { TanstackQueryProvider } from '@/providers/tanstackQuery.provider';
import type { Metadata } from "next";
import { Bounce, ToastContainer } from 'react-toastify';
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true">
      <ToastContainer position="top-right"
        autoClose={5000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick={false}
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        theme="light"
        transition={Bounce}/>
        <TanstackQueryProvider>
          <Header />
          <div className="mt-16 w-full h-[calc(100dvh-64px)] overflow-hidden">
            {children}
          </div>
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
