import { Header } from '@/components/containers/header/header';
import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="mt-16 w-[100dvw] h-[calc(100dvh-64px)]">
          {children}
        </div>
      </body>
    </html>
  );
}
